[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# ✅ PRIORITÉ: l'API d'abord
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/soil/:splat"
  status = 200
  force = true

# ✅ SPA fallback ensuite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
