[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Tout ce qui commence par /api/ va vers la Function "soil"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/soil/:splat"
  status = 200

